@startuml entities_of_prescription

!include ./style.pu

entity "都道府県" as prefectures <<M,MASTER_MARK_COLOR>> {
    + 都道府県名 [PK]
    --
    都道府県番号
}

entity "保険者" as insurers <<M,MASTER_MARK_COLOR>> {
    + 保険者番号 [PK]
    --
    保険者名
    保険者所在地
}
entity "公費負担者" as public_bears <<M,MASTER_MARK_COLOR>> {
    + 公費負担者番号 [PK]
    --
    公費負担者名
    公費負担者所在地
}

entity "病院情報" as hospital <<M,MASTER_MARK_COLOR>> {
    + 医療機関コード [PK]
    --
    病院名
    住所
    電話番号
}

package "処方箋データ" as target_system {
    entity "患者情報" as patients <<E,TRANSACTION_MARK_COLOR>> ENTITY {
        + 患者ID [PK]
        --
        名前
        生年月日
        年齢
        性別
        区分
        保険者番号
        公費負担者番号
        公費負担医療の受給者番号
        被保険者証・被保険者手帳の記号・番号
    }

    entity "処方箋情報" as consultation <<主, TRANSACTION_MARK_COLOR>> MAIN_ENTITY {
        + 処方箋ID [PK]
        --
        交付年月日
        都道府県番号
        点数表番号
        医療機関コード
        保険医名
        患者ID
        医薬品コード
        処方箋の使用期間
        保険医療機関への疑義紹介した上での調剤の有無
        保険医療機関への情報提供の有無
        調剤済年月日
        保険薬局の所在地
        名称保険薬剤師氏名
        公費負担者番号
        公費負担者医療の受給者番号
    }
    entity "処方した薬情報" as prescribedMedicine <<E, TRANSACTION_MARK_COLOR>> ENTITY {
        + 医薬品コード [PK]
        --
        医薬品名
        用量
        使用頻度
        使用部位
        ジェネリックへの変更可否
    }
}
@enduml