@startuml relation_between_entities
    !include ./prescription.pu

    consultation ||-d-|| patients
    patients }|-|| insurers
    patients -d- public_bears
    consultation ||-l-|{ prescribedMedicine
    consultation }|-|| hospital
    insurers }|-do-|| prefectures
    hospital }|-|| prefectures

@enduml