@startuml style

'メインEntityの色
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define ENTITY #FCE4D6-F8CBAD

' その他のEntityの色
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00

'デフォルトのスタイルを設定(本指定はclassで行う必要あり)
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}
@enduml